development:
  adapter: postgresql
  encoding: unicode
  database: spruceling_development
  host: localhost
  pool: 5
  username: matt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: spruceling_test
  host: localhost
  pool: 5
  username: matt
  password:

staging:
  adapter: postgresql
  uri: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  uri: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: 5